# rule all:
#     output: touch("{accession}.all")
#     input: "data/{accession}/{accession}.fastq"

rule download_sra:
    output: 
        "data/{accession}/{accession}_1.fastq",
        "data/{accession}/{accession}_2.fastq"
    resources: 
        time_min=60, 
        mem_mb=8000, 
        cpus=6
    shell: "fasterq-dump {wildcards.accession} -O data/{wildcards.accession} -e {resources.cpus}"

rule fastp:
    input: 
        r1 = "data/{accession}/{accession}_1.fastq",
        r2 = "data/{accession}/{accession}_2.fastq"
    output: 
        r1 = "data/{accession}/{accession}_1.fastp.fastq",
        r2 = "data/{accession}/{accession}_2.fastp.fastq"
    resources:
        cpus = 6,
        mem_mb = 24000
    shell: "fastp -i {input.r1} -I {input.r2} -o {output.r1} -O {output.r2} --thread {resources.cpus}"